version: 2

updates:
  # npm - site package
  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - site

  # npm - host package
  - package-ecosystem: npm
    directory: /host
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - host

  # npm - desktop package
  - package-ecosystem: npm
    directory: /desktop
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - desktop

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
